version: 2
jobs:
  build:
    docker:
      - image: tesyolan/emotion-recognition-service:latest
    steps:
      - checkout
      - run:
          name: Start Test
          command: python3.6 -m unittest test_rpc_call.TestSuiteGrpc
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
