version: 2
jobs:
  build:
    docker:
      - image: tesyolan/emotion-recognition-service:latest
    steps:
      - checkout
      - run:
          - name: Start command
          - command: python3.6 script.py
      - run:
          - name: Query Image
          - command: python3.6 test_rpc_call.py --test_grpc 8001
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
